# lightning.pytorch==2.0.2
data:
  datasetComputationClass: ml.regression.drn.dataset_making.LayerClustersTensorMaker
  multiprocess_loader: false
  keepOnGpu: cuda:2

model:
  drn:
    init_args:
      hidden_dim: 20
      k: 20
      dropout: 0.3

sigma_over_e_callback:
  fit_data: full
  every_n_epochs: 20
  skip_first_n_epochs: 30

trainer:
  accelerator: gpu
  devices: [2]
  callbacks:
    # - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    #   init_args:
    #     every_n_epochs: 2
    #     save_last: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: Loss/Validation_epoch
        mode: min
        save_top_k: 10
        every_n_epochs: 10
        save_last: true   
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: Loss/Validation_epoch
        patience: 80
    - class_path: ml.regression.drn.callbacks.simple_plots.SimplePlotsCallback
      init_args:
        every_n_epochs: 10
    
  max_epochs: 300
  log_every_n_steps: 1

