# lightning.pytorch==2.0.2
data:
  datasetComputationClass: ml.regression.drn.dataset_making.RechitsTensorMaker
  multiprocess_loader: false
  keepOnGpu: cuda:2
  batch_size: 1024

sigma_over_e_callback:
  fit_data: full
  every_n_epochs: 4

trainer:
  accelerator: gpu
  devices: [2]
  callbacks:
    # - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    #   init_args:
    #     every_n_epochs: 2
    #     save_last: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: Loss/Validation_epoch
        mode: min
        save_top_k: 20
        every_n_epochs: 2
        save_last: true   
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: Loss/Validation_epoch
        patience: 8
  max_epochs: 100
