# lightning.pytorch==2.0.2
seed_everything: 2692386656
trainer:
  accelerator: gpu
  strategy: auto
  devices:
  - 3
  num_nodes: 1
  precision: 32-true
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 5
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: 0.5
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: true
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  drn:
    class_path: ml.dynamic_reduction_network.DynamicReductionNetwork
    init_args:
      input_dim: 4
      hidden_dim: 20
      output_dim: 1
      k: 10
      aggr: add
      norm:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      dropout: 0.3
  loss:
    class_path: ml.regression.drn.modules.RatioCorrectedLoss
    init_args:
      coefs:
      - -0.2597882
      - -0.24326517
      - 1.01537901
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.001
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      weight_decay: 0.001
      amsgrad: false
      maximize: false
      foreach: null
      capturable: false
      differentiable: false
      fused: null
  lr_scheduler:
    class_path: ml.regression.drn.modules.CyclicLRWithRestartsAdapter
    init_args:
      restart_period: 80
      t_mult: 1.2
      verbose: false
      policy: cosine
      policy_fn: null
      min_lr: 1.0e-07
      gamma: 1.0
      triangular_step: 0.5
data:
  reader:
    class_path: ntupleReaders.clue_ntuple_reader.ClueNtupleReader
    init_args:
      version: v40
      clueParams: cmssw
      datatype: sim_proton_v46_patchMIP
  datasetComputationClass: ml.regression.drn.dataset_making.LayerClustersTensorMaker
  transformFct: null
  multiprocess_loader: false
  batch_size: 16384
  keepOnGpu: cuda:3
sigma_over_e_callback:
  fit_data: full
  every_n_epochs: 2
  multiprocess_fit: forkserver
  debug_mode: false
  addFitResultUsingBareData: true
